api-addr: :1633
bootnode: "/ip4/18.216.66.9/tcp/1634/p2p/16Uiu2HAmExSHEV4FPxQMfgREDX6KX5BhyUb2aLQQTP5wgUyc7un9"
#- /dnsaddr/bootnode.ethswarm.org
bootnode-mode: true
clef-signer-enable: false
clef-signer-endpoint: ""
clef-signer-ethereum-address: ""
config: ""
cors-allowed-origins: ["*"]
data-dir: C:/voyagerdata
db-block-cache-capacity: "33554432"
db-capacity: "5000000"
db-disable-seeks-compaction: false
db-open-files-limit: "200"
db-write-buffer-size: "33554432"
debug-api-addr: :1635
debug-api-enable: true
gateway-mode: true
global-pinning-enable: true
help: false
nat-addr: "18.216.66.9:1634"
network-id: "18888"
p2p-addr: :1634
p2p-quic-enable: true
p2p-ws-enable: true
password: "xie5532168"
password-file: ""
payment-early: "1000000000000"
payment-threshold: "10000000000000"
payment-tolerance: "50000000000000"
resolver-options: []
standalone: false
swap-enable: true
swap-endpoint: http://18.216.66.9:8545
swap-factory-address: "0x18aBF8b99c3AF1448400bFbd45F24701FD39da31"
swap-initial-deposit: "0"
tracing-enable: false
tracing-endpoint: 127.0.0.1:6831
tracing-service-name: fish
verbosity: info
welcome-message: ""